/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface SolidLoginPopup {
    'popup': string;
  }
  interface SolidLoginPopupAttributes extends StencilHTMLAttributes {
    'popup'?: string;
  }

  interface SolidLogin {
    'callback': string;
  }
  interface SolidLoginAttributes extends StencilHTMLAttributes {
    'callback'?: string;
  }

  interface SolidProviderSelect {}
  interface SolidProviderSelectAttributes extends StencilHTMLAttributes {
    'onProviderChanged'?: (event: CustomEvent) => void;
  }

  interface MyComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }

  interface SolidForm {}
  interface SolidFormAttributes extends StencilHTMLAttributes {}

  interface PostCreate {
    'webid': string;
  }
  interface PostCreateAttributes extends StencilHTMLAttributes {
    'webid'?: string;
  }

  interface PostList {
    'webid': string;
  }
  interface PostListAttributes extends StencilHTMLAttributes {
    'webid'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SolidLoginPopup': Components.SolidLoginPopup;
    'SolidLogin': Components.SolidLogin;
    'SolidProviderSelect': Components.SolidProviderSelect;
    'MyComponent': Components.MyComponent;
    'SolidForm': Components.SolidForm;
    'PostCreate': Components.PostCreate;
    'PostList': Components.PostList;
  }

  interface StencilIntrinsicElements {
    'solid-login-popup': Components.SolidLoginPopupAttributes;
    'solid-login': Components.SolidLoginAttributes;
    'solid-provider-select': Components.SolidProviderSelectAttributes;
    'my-component': Components.MyComponentAttributes;
    'solid-form': Components.SolidFormAttributes;
    'post-create': Components.PostCreateAttributes;
    'post-list': Components.PostListAttributes;
  }


  interface HTMLSolidLoginPopupElement extends Components.SolidLoginPopup, HTMLStencilElement {}
  var HTMLSolidLoginPopupElement: {
    prototype: HTMLSolidLoginPopupElement;
    new (): HTMLSolidLoginPopupElement;
  };

  interface HTMLSolidLoginElement extends Components.SolidLogin, HTMLStencilElement {}
  var HTMLSolidLoginElement: {
    prototype: HTMLSolidLoginElement;
    new (): HTMLSolidLoginElement;
  };

  interface HTMLSolidProviderSelectElement extends Components.SolidProviderSelect, HTMLStencilElement {}
  var HTMLSolidProviderSelectElement: {
    prototype: HTMLSolidProviderSelectElement;
    new (): HTMLSolidProviderSelectElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLSolidFormElement extends Components.SolidForm, HTMLStencilElement {}
  var HTMLSolidFormElement: {
    prototype: HTMLSolidFormElement;
    new (): HTMLSolidFormElement;
  };

  interface HTMLPostCreateElement extends Components.PostCreate, HTMLStencilElement {}
  var HTMLPostCreateElement: {
    prototype: HTMLPostCreateElement;
    new (): HTMLPostCreateElement;
  };

  interface HTMLPostListElement extends Components.PostList, HTMLStencilElement {}
  var HTMLPostListElement: {
    prototype: HTMLPostListElement;
    new (): HTMLPostListElement;
  };

  interface HTMLElementTagNameMap {
    'solid-login-popup': HTMLSolidLoginPopupElement
    'solid-login': HTMLSolidLoginElement
    'solid-provider-select': HTMLSolidProviderSelectElement
    'my-component': HTMLMyComponentElement
    'solid-form': HTMLSolidFormElement
    'post-create': HTMLPostCreateElement
    'post-list': HTMLPostListElement
  }

  interface ElementTagNameMap {
    'solid-login-popup': HTMLSolidLoginPopupElement;
    'solid-login': HTMLSolidLoginElement;
    'solid-provider-select': HTMLSolidProviderSelectElement;
    'my-component': HTMLMyComponentElement;
    'solid-form': HTMLSolidFormElement;
    'post-create': HTMLPostCreateElement;
    'post-list': HTMLPostListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
