/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }

  interface PostCreate {
    'webid': string;
  }
  interface PostCreateAttributes extends StencilHTMLAttributes {
    'webid'?: string;
  }

  interface PostList {
    'webid': string;
  }
  interface PostListAttributes extends StencilHTMLAttributes {
    'webid'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'PostCreate': Components.PostCreate;
    'PostList': Components.PostList;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'post-create': Components.PostCreateAttributes;
    'post-list': Components.PostListAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLPostCreateElement extends Components.PostCreate, HTMLStencilElement {}
  var HTMLPostCreateElement: {
    prototype: HTMLPostCreateElement;
    new (): HTMLPostCreateElement;
  };

  interface HTMLPostListElement extends Components.PostList, HTMLStencilElement {}
  var HTMLPostListElement: {
    prototype: HTMLPostListElement;
    new (): HTMLPostListElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'post-create': HTMLPostCreateElement
    'post-list': HTMLPostListElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'post-create': HTMLPostCreateElement;
    'post-list': HTMLPostListElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
